### ISSUE TITLE
[ALCOM] Local package management.

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#849] opened 2024-04-26 21:12 UTC
### Summary / 概要

ALCOM already supports using local packages that are added in VCC, but has no GUI to manage those inside of ALCOM.

settings.json -> userPackageFolders

It is a json list refering to local unpacked package folders, format being:
"D:\\Unity\\Packages\\com.vendor.package",

![image](https://github.com/vrc-get/vrc-get/assets/8122264/3292e1f7-6216-4771-87e3-8e90567e8a13)

Layout could be a simple split view, giving less percentage of space to local packages as these are lower priority.

### Purpose / 目的

Adding local package management helps to test packages or using paid, or otherwise licensed packages that should not be in a repository.
It is also, as far as I can see, the last major feature missing for feature-parity with VCC.

**Comment by anatawa12** [comment] 2024-04-27 05:11
Thank you for ui suggestion!
We already have issue #553.

**Comment by anatawa12** [comment] 2024-04-27 05:11
Duplicate of #553

**Closed by anatawa12** 2024-04-27 05:11 UTC
Labels: enhancement, vrc-get-gui
