### ISSUE TITLE
Use ALCOM as the app link for vcc://vpm/add-repo

### ISSUE THREAD

**Issue by Dreadrith** [vrc-get/vrc-get#823] opened 2024-04-21 11:20 UTC
### Summary / 概要

Make ALCOM capable of using `vcc://vpm/add-repo` to easily add VPM repositories to it.

### Purpose / 目的

A lot of creators share links that use `vcc://vpm/add-repo` to allow users to add VPM repositories to VCC with one click. It'd be nice to allow ALCOM to open them instead of VCC for convenience.

### Additional context / 補足

The only parameters I know of that can be passed to it are:
- `url` -> The url of the listing.json
- `headers` -> written in `key:value` format. Example: `&headers=Authorization:Bearer github_pat_....`
- I think more headers could be passed to it by writing it again in the same format, but I haven't tested that.

**Comment by anatawa12** [comment] 2024-04-21 12:46
I've planned for that but tauri doesn't support that in v1 so I'm considering migrate to v2 beta or use some workaround.

Duplicate of #391

**Comment by anatawa12** [comment] 2024-04-21 12:46
Duplicate of https://github.com/vrc-get/vrc-get/issues/391

**Closed** 2024-04-21 12:46 UTC
Labels: enhancement, vrc-get-gui
