### ISSUE TITLE
Installing / Upgrading package took long time without notice before confirm prompt is shown.

### ISSUE THREAD

**Issue by ChinatsuHS** [vrc-get/vrc-get#1517] opened 2024-09-13 22:48 UTC
### Summary / 概要

Currently in the project manager window all you can see when fetching any package from a repository is the spinning refresh icon, It would be great if we could get some clearer indication or even a verbose log of the progress of the fetch from repositories, as it can take between 1 to 30 minutes to fetch the package majority of the times with no clear visual if the fetch is still running or got stuck due to a error.

### Purpose / 目的

A clear indication that a package fetch process is X% finished or that the fetch speed has dropped significantly on the project manage window.

![image](https://github.com/user-attachments/assets/226b3db6-9434-4e1a-8625-e8d82dfe12b6)

**Comment by anatawa12** [comment] 2024-09-14 16:46
>  it can take between 1 to 30 minutes to fetch the package majority of the times 

Umm... it seem weird to took such long time (with reasonably fast connection). are you in very slow network connection?

**Comment by ChinatsuHS** [comment] 2024-09-14 17:45
> Umm... it seem weird to took such long time (with reasonably fast connection). are you in very slow network connection?

not at all unless 2.5 Gbps is considered slow (up to 350 MB/s download and 150 MB/s Upload)

**Comment by JustBuddy** [comment] 2024-09-14 17:49
ALCOM (vrc-get) barely need 10 seconds to do any operation in that regard. 
You might have one package repository in your list that you got a bad connection to. 
I have around 24 repository in ALCOM, and barely wait for any operation.

**Comment by ChinatsuHS** [comment] 2024-09-14 18:26
yea..tried fetching pumkin tools and it took about 8 minutes, only a spinning icon as indication something was running

**Comment by JustBuddy** [comment] 2024-09-14 20:00
> yea..tried fetching pumkin tools and it took about 8 minutes, only a spinning icon as indication something was running

Can't replicate, just takes a few seconds.
Something else is up.

Repo: https://rurre.github.io/vpm/

**Comment by Spokeek** [comment] 2024-09-14 23:52
@ChinatsuHS as now ALCOM can allow to export the list of repositories, can you maybe provide what you use so we can try to replicate your case ?

**Comment by ChinatsuHS** [comment] 2024-09-15 08:44
> @ChinatsuHS as now ALCOM can allow to export the list of repositories, can you maybe provide what you use so we can try to replicate your case ?

Will do when i get home later,
There are no unfamiliar repositories in there: 
Dreadriths packages
Pumkin tools packages 
Modular Avatar packages
Face-Emo
and the vrchat sdk ones.

out of my head

**Comment by Spokeek** [comment] 2024-09-15 11:04
Unsure if we can fix this if we can't reproduce, if it is a regular repo that takes a while to update, maybe contact the person responsible to see why specifically.

**Comment by ChinatsuHS** [comment] 2024-09-15 14:22
![image](https://github.com/user-attachments/assets/fd2eb404-ab0f-4fb4-9dfb-1c18bc33960d)

Here is a debug log view of the most recent package update (11 minutes to fetch the files(this happens with all packages)) and all repositories in Alcom.

**Comment by Spokeek** [comment] 2024-09-15 14:25
What i see based on the logs is that the repo update didn't take that much time as it was mostly cache hit.
But the one was the installation of vrcfury in your project.

Maybe your Unity project was heavy enough for Unity to take a long time to install the package. Can you try it specifically to install vrcfury but within an empty project, see if you see a difference ?

**Comment by anatawa12** [comment] 2024-09-15 14:29
1) Could you share the full list of repositories? you can export repository list from drop down menu at upper left on repositories page.

2) it looks the shot includes log about installing packages. Is the issue actually about fetching repositories (on opening project page or clicking spinner) or installing pakages?

**Comment by ChinatsuHS** [comment] 2024-09-15 14:33
Q1:  [repositories.txt](https://github.com/user-attachments/files/17006116/repositories.txt)

Q2: the issue is from the moment one hits install/update package to actually being able to apply the install/update.
> no progress visible aside from the spinning icon for 1-30 minutes.

**Comment by Spokeek** [comment] 2024-09-15 14:35
Is it when you try to update one specific package or update them all with the "update all" button ?

**Comment by ChinatsuHS** [comment] 2024-09-15 14:35
> Is it when you try to update one specific package or update them all with the "update all" button ?

both situations

**Comment by ChinatsuHS** [comment] 2024-09-15 14:36
on a smaller project it is a bit faster but that could also have been because it was getting it from cache already

**Comment by anatawa12** [comment] 2024-09-15 14:40
> the issue is from the moment one hits install/update package to actually being able to apply the install/update.

it looks legacy assets search (filesystem operation) took long time. (vrcfury has  legacy assets settings).

can you try installing/reinstalling/updating packages without legacyassets like NDMF?

**Comment by Spokeek** [comment] 2024-09-15 14:41
oh, one good thing to ask, what are your pc specs graded (in a general sense, (like old, decent, powerful) and on what kind of hard drive is your project stored ? (HDD, SSD, etc)

**Comment by ChinatsuHS** [comment] 2024-09-15 14:44
> oh, one good thing to ask, what are your pc specs graded in a general sense, (like old, decent, powerful) and on what kind of hard drive is your project stored ? (HDD, SSD, etc)

![image](https://github.com/user-attachments/assets/5d15cf45-f143-422b-85e0-bb7a2d14c8b5)
mid range i suppose: Project is on a 1TB HDD as my 64GB SSD is too small to put unity stuff in next to windows and python stuff.

**Comment by anatawa12** [comment] 2024-09-15 17:35
@ChinatsuHS can you try installing/reinstalling/updating packages without legacyassets(legacyfiles or legacyfiles) like NDMF?

**Comment by ChinatsuHS** [comment] 2024-09-16 15:11
Yea..think my project(s) get too big fast :D 

But the issue/feature i initially asked for was some sort of progress or even status info on the Manage Project window aside from just a spinning icon...
Could be as simple as a verbose text at a statusbar on top or at the bottom [ fetching package XXXXX @ XXXX MB/s XX.XXs/XX.XXs left ]

**Comment by anatawa12** [comment] 2024-09-17 04:58
@ChinatsuHS 

What you in initially asked is progress info for fetching repository. We understand that.
However, it looks the problem you experienced is there are no progress info prepareing for installing package (after clicking install/upgrade button on each package).
To provide suitable progress information, we need to determine which phase of prepareing for installing package is actually slow.
This is why I'm asking for installing packages without legacyFiles/legacyFolders are slow or not. If slow, shared part is slow and if not, finding for legacy assets are slow part and where we should provide progress information.


Actually, fetching repositories are performed on opening Manage Project (package list) page and before clicking install button, and downloading package archive is performed after confirming dialog for install.
Therefore, it looks adding progress information for downloading package or repository does not help with your problem.

**Comment by ChinatsuHS** [comment] 2024-09-17 23:37
ok.. so the point that is slow is after opening the Manage project window

 but the moment one hits to update/install the package.
Before you get the popup to cancel or apply the install/update.

hmm not sure if related but : 
![image](https://github.com/user-attachments/assets/091823a0-ae0d-45bf-8ca9-50efbbb8e66e)

this happens in the log on a new project when installing the packages

**Comment by anatawa12** [comment] 2024-09-18 11:50
> hmm not sure if related but :
> 
> this happens in the log on a new project when installing the packages

which package was installed for the project? and which package did you installed? 

your error itself does not have enough information. (for assumption)
logs are desgined to provide enough information throughout, but might not enough with partial information.

And according to the log, FileSystem reported those entries are exists in the Packages directory but accessing that would report not exists.
Such weird filesystem behavior likely to happens with some remote drive drivers like OneDrive, GoogleDrive, Dropbox or others.
Are you storing your data inside such drive services?

Finally, sorry for ask for many times, could you try installing (downgrading / upgrading) NDMF, vpm resolver or some other packages without legayFiles and legacyFiles?
If this is not slow, we can identify the actual slow part, where it's better to provide progress information.

**Comment by ChinatsuHS** [comment] 2024-09-18 20:58
A complete blank project with just the vrcsdk takes appr. 1 minute per package/repo before the popup shows to apply the install/update.

doesn't matter what package i want to install (all give the same error in the log yet install just fine)

**Comment by anatawa12** [comment] 2024-09-22 03:49
Sorry for late response. I fail to notice your response in inbox.

> A complete blank project with just the vrcsdk takes appr. 1 minute per package/repo before the popup shows to apply the install/update.
> 
> doesn't matter what package i want to install (all give the same error in the log yet install just fine)

Which package did you installed?

Sorry for saying again and again, to identify which phase of installing package is actually slow, I need to know if it's fast to install packages without legacyFiles / legacyFolders.

If you don't want to follow my instruction like installing vpm resolver or NDMF, could you say "No I don't want to install XXXX" explicitly with reasons?

**Comment by ChinatsuHS** [comment] 2024-09-29 12:58
this was vpm resolver, audiolink and gogoloco.

**Comment by anatawa12** [comment] 2024-09-29 15:53
Umm....

I think I need more info to determine which phase of installing package took long time.

I'll add more logs in next prerelease.

**Comment by anatawa12** [comment] 2024-09-30 14:08
@ChinatsuHS Sorry for ask again again and again.

Could you try the latest build that can be downloaded from https://github.com/vrc-get/vrc-get/actions/runs/11106747045?

Click x86_64-pc-windows-msvc and extract, and please try `ALCOM.exe` at the root of crate.

After trying to install some package (if possible please try installing both packages with legacy assets and without legacy assets individually), Please send me the log file that can be opened with "log folder" button on the logs page.

**Comment by ChinatsuHS** [comment] 2024-10-02 13:15
@anatawa12 [vrc-get-2024-10-02_13-02-06.351918.log](https://github.com/user-attachments/files/17229698/vrc-get-2024-10-02_13-02-06.351918.log)

This is on a completely empty new project (first installed vrcsdk base and avatars and afterwards the other packages i always use)
On this empty project it went reasonable fast, with Legacy assets you mean everything that is in assets and not in packages?

**Comment by anatawa12** [comment] 2024-10-02 13:44
> This is on a completely empty new project (first installed vrcsdk base and avatars and afterwards the other packages i always use)

Could you try with your (relatively big?) project you used to test and send me the log file?

> On this empty project it went reasonable fast, with Legacy assets you mean everything that is in assets and not in packages?

I call legacyFiles and legacyFolders as legacy assets.

Most VPM packages that previously distributed as unitypackage will specify legacyFolders or legacyFiles to remove unitypackage version of same tool on installing VPM package.
This will prevents problem with installing same asset (tool) multiple time in one project. (e.g. GUID Conflict).

When I saied packages with legacy assets, I mean package that specified legacyFiles or legacyFolders.
For example, `com.vrchat.core.vpm-resolver` and `nadena.dev.ndmf` are packages without legacy assets.
On the other hand, `com.vrcfury.vrcfury` and `vrchat.blackstartx.gesture-manager` are packages with legacy assets.

Package can specify legacy aseets in two form: one is path form and the other is GUID form.
The path form is very simple; ALCOM (or VCC) will find the path from project and remove the directory / file from project.
However, GUID form is a little complicated. With GUID form of legacy aseets, ALCOM (or VCC) have to find all assets on your project and read all `.meta` files, and find file / directory with same GUID.
This phase can took several seconds depending on size of your project.

**Comment by anatawa12** [comment] 2024-10-02 13:51
In your log file, many packages are installed at once.

In previous comments, I asked for installing vpm resolver or NDMF and you said "doesn't matter what package i want to install".
I thought you're installing NDMF only and no other packages are not installed at once, but I did not asked.
Did you installed some packages along with NDMF or vpm-resolver, when you're installing package for testing?
If so, sorry for not explaining well.

**Comment by ChinatsuHS** [comment] 2024-10-02 15:08
> Thank you for log file.
> 
> > This is on a completely empty new project (first installed vrcsdk base and avatars and afterwards the other packages i always use)
> 
> Could you try with your (relatively big?) project you used to test and send me the log file?
> 
> > On this empty project it went reasonable fast, with Legacy assets you mean everything that is in assets and not in packages?
> 
> I call legacyFiles and legacyFolders as legacy assets.
> 
> Most VPM packages that previously distributed as unitypackage will specify legacyFolders or legacyFiles to remove unitypackage version of same tool on installing VPM package. This will prevents problem with installing same asset (tool) multiple time in one project. (e.g. GUID Conflict).
> 
> When I saied packages with legacy assets, I mean package that specified legacyFiles or legacyFolders. For example, `com.vrchat.core.vpm-resolver` and `nadena.dev.ndmf` are packages without legacy assets. On the other hand, `com.vrcfury.vrcfury` and `vrchat.blackstartx.gesture-manager` are packages with legacy assets.
> 
> Package can specify legacy aseets in two form: one is path form and the other is GUID form. The path form is very simple; ALCOM (or VCC) will find the path from project and remove the directory / file from project. However, GUID form is a little complicated. With GUID form of legacy aseets, ALCOM (or VCC) have to find all assets on your project and read all `.meta` files, and find file / directory with same GUID. This phase can took several seconds depending on size of your project.

ah .. ok yea than it makes sense as it is mostly VRCfury and the likes that take forever (as those get the most updates also).

**Comment by anatawa12** [comment] 2024-10-02 15:50
> Would be in line with what i was requesting.. a better way to know what is going on instead4 of just a spinning icon).

I may add some note that tells finding legacy assets in project is in progress.
(but this is very hard with current architecture and there is ui design problem)

Not only that, finding legacy assets that are already installed mostly be useless so I think ALCOM can skip finding for legacy assets for upgrading package.
(due to internal architecture, it's a little hard to implement and I thought finding legacy assets are not too heavy so I did not implemented. With your report, I'll implement this skip feature in the near feature. This is easier than adding progress info.)

I'm going to close this issue when either of the two feature is implemented.
Is this acceptable?
Of course, I'll file another issue for the other issue.

**Closed** 2024-10-02 17:16 UTC
Labels: enhancement, vrc-get-gui
