### ISSUE TITLE
[GUI] Reorder VPM list entries.

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#992] opened 2024-05-18 15:28 UTC
### Summary / 概要

I would love to be able to reorder my package sources directly in ALCOM.

### Purpose / 目的

The order in which listings are in settings.json directly influence in which order the packages are in ALCOM (and VCC).
I would love to see the packages I use most of the time higher up, right now I have to edit the settings.json manually.

**Comment by anatawa12** [comment] 2024-05-18 15:31
duplicate of #654

**Closed by anatawa12** 2024-05-18 15:31 UTC
Labels: enhancement, vrc-get-gui
