### ISSUE TITLE
The installer does not automatically promote to windows administrator privileges

### ISSUE THREAD

**Issue by TheSmileCat** [vrc-get/vrc-get#1516] opened 2024-09-13 13:00 UTC
### Description of the bug / バグの説明

When I installed "D:\Program Files\", the installer did not automatically grant rights, but instead gave me an error.
The permissions of this folder have not been changed manually since Windows was installed.
Of course, if you do an auto-upgrade, the auto-upgraded installer also fails.

### Steps to Reproduce / 再現手順

Directly double-click to open the installer, select "D:\Program Files\", and click Start installation.

### Expected Behavior / 想定される挙動

A UAC window popped up automatically asking me to confirm my administrator privileges and install it.

### Screenshots / スクリーンショット

![5eba062cafb114701e3c971c01e8b48a](https://github.com/user-attachments/assets/a5acf1a0-c278-4dd7-9f86-5ae5ef2b150d)
![image](https://github.com/user-attachments/assets/9bda282d-b24e-4902-bc1a-d1e34c50b574)

### Software Version / バージョン情報

0.1.15 (eb5c2ca120a2a8dea3634811272160868427c096)

### OS

Windows 10.0.22631 - x86_64

### Webview Version / Webviewバージョン

128.0.2739.67

**Comment by anatawa12** [comment] 2024-09-13 19:25
Installing ALCOM system-wide is not supported.

duplicate of #1022 (issue for system install support)

see tauri-apps/tauri#9609 tauri-apps/tauri#9836 #976 #1020 #1021

**Closed** 2024-09-13 19:26 UTC
Labels: bug, vrc-get-gui
