### ISSUE TITLE
Can't open URLs in AppImage version on KDE 6

### ISSUE THREAD

**Issue by hypevhs** [vrc-get/vrc-get#1251] opened 2024-07-10 23:22 UTC
### Description of the bug / バグの説明

When I click anything that should open my browser to a URL, for example "Open An Issue" or "See Changelog", it does nothing.

I'm using the AppImage from GitHub CI, and my DE is KDE 6.

### Steps to Reproduce / 再現手順

1. Open ALCOM AppImage on KDE 6
2. Click Settings
3. Click "OPEN AN ISSUE"
4. Observe: Nothing happens

### Expected Behavior / 想定される挙動

My browser should open the URL.

### Software Version / バージョン情報

0.1.9

### OS

Arch Linux, KDE 6

### Additional context / 補足

Q: Why does this happen?

When building an AppImage, Tauri CLI will also include a copy of xdg-open from the host. In ALCOM CI's case, this is based on Ubuntu 22.04.
This xdg-open is old and has a bug where it does not consider KDE 6 at all. It silently does nothing if KDE_SESSION_VERSION is not 4 or 5. This was fixed in later releases of xdg-open.

This could be considered a bug in Tauri. I'm opening this here to discuss workarounds in the meantime

Ideas for solution:
- Can we opt-out of Tauri bundling Ubuntu's old/buggy xdg-open?
- Can we remove the xdg-open from the tarball before it gets packaged as an AppImage?
- Instead of using Tauri's shell.open, can we call xdg-open directly if we detect ALCOM is running as an AppImage?

**Comment by anatawa12** [comment] 2024-07-10 23:48
Duplicate of #934 and upstreamed as https://github.com/tauri-apps/tauri/issues/10078 but thank you for detailed information what happened.

**Closed by anatawa12** 2024-07-10 23:48 UTC
Labels: bug, vrc-get-gui
