### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by dammerungmonat** [vrc-get/vrc-get#1092] opened 2024-06-08 13:57 UTC
### Description of the bug / バグの説明

When I download a Win64 executable, the downloaded executable is reported as malware.

### Steps to Reproduce / 再現手順

Case1 :
-1. Open https://vrc-get.anatawa12.com/alcom/
-2. Click 「Download the Latest Version」

Case2 :
-1. Open https://github.com/vrc-get/vrc-get/releases
-2. Click 「ALCOM-0.1.6-x86_64-setup.exe」 or 「ALCOM-0.1.7-x86_64-setup.exe」
 * This did not occur when the target was 0.1.5 or lower.

Case3: 
-1. Open ALCOM application(version 0.1.5 or lower)
-2. Accept version up dialog

### Expected Behavior / 想定される挙動

Must not be detected as malware

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/497468/e7c628e7-20a2-424d-84d1-819721a98053)

### Software Version / バージョン情報

0.1.5

### OS

Windows 10 Home  22H2 19045.4412

### Additional context / 補足

・Windows Defender
- Anti malware client : 4.18.24050.7
- Engine : 1.1.24050.5
- Anti virus : 1.413.169.0
- Anti spyware : 1.413.169.0

・NordVPN
- version : 7.24.4.0

・Check result with VirusTotal
* Detection was made VT.
- https://www.virustotal.com/gui/url/3355949421b0498315eda46ee398ddb06ed3319b15bf5553fe06f40bf0aaff7d/detection

**Comment by anatawa12** [comment] 2024-06-08 14:02
Thank you for report. 
It looks duplicate of #1091

**Comment by anatawa12** [comment] 2024-06-08 14:03
duplicate of #1091

**Closed by anatawa12** 2024-06-08 14:03 UTC
Labels: bug, vrc-get-gui
