### ISSUE TITLE
Resize Project Tables Header

### ISSUE THREAD

**Issue by Dog** [vrc-get/vrc-get#854] opened 2024-04-28 08:14 UTC
### Summary / 概要

Currently if a long path name is used, the window for ALCom must be resized to accommodate the full path.

### Purpose / 目的

If a long path name - such as if you are using iCloud as a project location - then the window size must be resized to accommodate the path. The window needs to be made bigger in order to see the rest of the functionality, such as the open, manage, and backup buttons. I think it would be better to dictate the size of the Name tab based on the project names, rather than the longest path.

### Additional context / 補足

<img width="1748" alt="Screenshot 2024-04-28 at 1 13 41 AM" src="https://github.com/vrc-get/vrc-get/assets/5172592/d0bb63bd-77f0-4617-93a3-793f807d0115">

**Comment by anatawa12** [comment] 2024-04-28 08:18
Duplicate of #459

**Closed by anatawa12** 2024-04-28 08:18 UTC
Labels: enhancement, vrc-get-gui
